### PR TITLE
feat: support prometheus format_query endpoint

### PR DESCRIPTION
**Pull request by tisonkun**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

_PLEASE DO NOT LEAVE THIS EMPTY !!!_

Implement `format_query` endpoint.

```
curl -i 'http://localhost:4000/v1/prometheus/api/v1/format_query?query=foo/bar'
HTTP/1.1 200 OK
content-type: application/json
content-length: 39
date: Fri, 10 Nov 2023 08:56:47 GMT

{"status":"success","data":"foo / bar"}
```

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

This closes https://github.com/GreptimeTeam/greptimedb/issues/1540.

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @waynexia @yuanbohan

**Review by yuanbohan — APPROVED** [review]
LGTM

**Comment by yuanbohan** [comment]
https://prometheus.io/docs/prometheus/latest/querying/api/#formatting-query-expressions

this may help reviewers

**Comment by tisonkun** [comment]
@yuanbohan  FYI - as this the last subtask for "SHOULD" in https://github.com/GreptimeTeam/greptimedb/issues/1016, perhaps we can close that issue once this PR gets merged.

**Comment by yuanbohan** [comment]
> @yuanbohan  FYI - as this the last subtask for "SHOULD" in https://github.com/GreptimeTeam/greptimedb/issues/1016, perhaps we can close that issue once this PR gets merged.

agree @waynexia

**Review by waynexia — APPROVED** [review]
LGTM

**Comment by waynexia** [comment]
> > @yuanbohan  FYI - as this the last subtask for "SHOULD" in #1016, perhaps we can close that issue once this PR gets merged.
> 
> agree @waynexia

After this PR we can make a new round of tests against prometheus to check if we are compatible on the API level.

**Pull request merged**
