### PR TITLE
fix(metasrv)!: do not overwrite boolean options unconditionally

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Before this patch, `use_memory_store` and `disable_region_failover` cannot be set via config file or env because they will always be overwritten by cli options, even if it's not provided in cli args.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by waynexia** [comment]
This is a breaking change. Now those two options need an extra param `true`/`false` to specify their value

**Review by killme2008 — APPROVED** [review]
Good catch!

**Comment by waynexia** [comment]
> Good catch!

@niebayes report it 👍

**Review by fengjiachun — APPROVED** [review]
LGTM

**Pull request merged**
