### PR TITLE
refactor: use toml2docs to generate config docs

### PR DESCRIPTION
**Pull request by zyy17**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

It may be a big PR, but most are the docs and configs.

To resolve the consistency between docs and actual configurations(it bothers me a lot that I have to check the code again and again), I wrote a small tool called [`toml2docs`](https://github.com/zyy17/toml2docs/tree/main) to help me generate markdown docs from toml files.

In this PR:

- The good docs need a well-commented toml example. I read all the `*Option` structures again and added more precise comments in every `*.example.toml`; 

- The `toml2docs` will extract the toml comments that start with `##` as the description for each fields;

- Add the makefile target `config-docs` to generate `config.md` in `config/`. It's very easy to execute the command by Docker, for example:
  
  ```
  make config-docs
  ```

  The `config-docs-template.md` is a template that used to generate the `config.md`.

  The `config.md` can be part of docs in [configuration](https://docs.greptime.com/user-guide/operations/configuration).

Other thought: IMO, the most elegant and efficient way to generate docs from the code directly and it needs some support from the toml crate. Maybe I will try it later. 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
LGTM. Let's add a CI tasks to ensure that the config docs are updated?

**Comment by zyy17** [comment]
> LGTM. Let's add a CI job to ensure that the config docs are updated?

sounds reasonable. Let me add the ci check.

**Review by waynexia — APPROVED** [review]
Awesome!

**Review by tisonkun — APPROVED** [review]
Cool!

**Review by evenyag — APPROVED** [review]
Cooooool! I really need this.

**Comment by killme2008** [comment]
What a great work!

**Pull request merged**
