### PR TITLE
feat(opertor): check if a database is in use before dropping it

### PR DESCRIPTION
**Pull request by etolbakov**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
https://github.com/GreptimeTeam/greptimedb/issues/4029

## What's changed and what's your intention?

check if a database/schema is in use before dropping it.

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

**Comment by etolbakov** [comment]
@killme2008 @waynexia 
Could you please take a look when you have free time?

also I'm not sure I understand why "CI / Unstable Fuzz Test (unstable_fuzz_create_table_standalone)" is failing if you could point me out I'll be very grateful 🙏

**Comment by WenyXu** [comment]
> @killme2008 @waynexia Could you please take a look when you have free time?
> 
> also I'm not sure I understand why "CI / Unstable Fuzz Test (unstable_fuzz_create_table_standalone)" is failing if you could point me out I'll be very grateful 🙏

The fuzz test will drop in-use database(`public`). Maybe we can create another database for testing instead of dropping the `public` directly?

**Comment by etolbakov** [comment]
Thank you Ruihang! I assume the rest is looks ok?

**Comment by WenyXu** [comment]
> Thank you Ruihang! I assume the rest is looks ok?

LGTM, But @waynexia he is Ruihang🤣

**Review by WenyXu — APPROVED** [review]

**Comment by etolbakov** [comment]
ohhhh....sorry Weny!!!!
My eyes played trick on me 😄 I really believed that Ruihang replied 🙈
My bad!

I would try tackling the test in the next couple of days

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@WenyXu There is a fuzz test failure
https://github.com/GreptimeTeam/greptimedb/actions/runs/9223815158/job/25388925971?pr=4035

**Review by waynexia — APPROVED** [review]
Looks good to @waynexia 😋

**Comment by etolbakov** [comment]
> @WenyXu There is a fuzz test failure https://github.com/GreptimeTeam/greptimedb/actions/runs/9223815158/job/25388925971?pr=4035

Many thanks to @WenyXu for fixing the failing test 🙏 
Linking the PR for the sake of the context.
https://github.com/GreptimeTeam/greptimedb/pull/4049

**Pull request merged**
