### PR TITLE
fix: dynamically get python udf from scripts table

### PR DESCRIPTION
**Pull request by xxxuuu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
https://github.com/GreptimeTeam/greptimedb/issues/2434
https://github.com/GreptimeTeam/greptimedb/issues/2532

## What's changed and what's your intention?

Add a `version` column to the scripts table and retrieve the latest script from the database before each script execution. If it is newer than the one in the local cache, recompile it.

This solves the problem where a script updated on one frontend in a cluster with multiple frontends does not take effect on the other frontends(because the script compilation cache cannot be updated, or the script is not registered).

**BREAKING CHANGE:**
Since the scripts are now obtained through scripts table, when executing via UDF in SQL, the script name must be used instead of the function name. This fixes the issue mentioned in https://github.com/GreptimeTeam/greptimedb/issues/2532. However, in cases where the script name and function name are different, if the program is using the function name, it will no longer work.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by tisonkun** [comment]
Thanks for your contribution!

You may take a look at https://github.com/GreptimeTeam/greptimedb/issues/3777. I suppose we may implement PyUDF in a more structural and proven way, said PL/Python, instead of hacky interpreting decorators and making new tribal rules.

For example, instead of making version names, we should use statement like:

```sql
CREATE FUNCTION pymax (a integer, b integer)
  RETURNS integer
AS $$
  if (a is None) or (b is None):
    return None
  if a > b:
    return a
  return b
$$ LANGUAGE plpython3u;
```

And then a function named `pymax` is always stored among the cluster, and no the confusing "name of file" vs. "name of function" vs. "name of name in args" things.

**Comment by tisonkun** [comment]
If you have other proposal, we can discuss in #3777. Generally it's good to discuss before implementing code, to avoid going in the wrong direction in the first place.

**Comment by xxxuuu** [comment]
> Thanks for your contribution!
> 
> You may take a look at #3777. I suppose we may implement PyUDF in a more structural and proven way, said PL/Python, instead of hacky interpreting decorators and making new tribal rules.
> 
> For example, instead of making version names, we should use statement like:
> 
> ```sql
> CREATE FUNCTION pymax (a integer, b integer)
>   RETURNS integer
> AS $$
>   if (a is None) or (b is None):
>     return None
>   if a > b:
>     return a
>   return b
> $$ LANGUAGE plpython3u;
> ```
> 
> And then a function named `pymax` is always stored among the cluster, and no the confusing "name of file" vs. "name of function" vs. "name of name in args" things.

Yes, this is a better approach, and I've also seen some other DBMSs doing it similar way. I will consider close this PR and then reevaluate/discuss this feature.

**Comment by tisonkun** [comment]
@xxxuuu Thanks for your reply. I'm open to respond in #3777 and support any effort to implement PyUDF in a cleaner `CREATE FUNCTION` way. If you're interested in this feature, feel free to drop a comment there so that we can describe more details.

**Comment by xxxuuu** [comment]
> I found that we can easily solve the original issue by banning "update scripts" but instead add a delete script API. Thus the script cache can be invalidated on deleted and otherwise it's always the corrected compiled cached ones.

Scripts created on one frontend are not registered on another frontend, and there is a similar issue with deletion. We still need to solve this issue.

**Comment by tisonkun** [comment]
> Scripts created on one frontend are not registered on another frontend, and there is a similar issue with deletion. We still need to solve this issue.

This is quite surprising. IIUC the script table should be identical with other tables, and thus it should be visible to every frontend instances.

**Comment by xxxuuu** [comment]
> This is quite surprising. IIUC the script table should not be different with other normal tables, and thus it should be visible to every frontend instances.

scripts table is visible, but it is not accessed when executed through SQL. Therefore, the script remains unregistered. This PR includes the modifications for this issue.

**Pull request closed without merging**
