### PR TITLE
feat: Changing default request body size limit.

### PR DESCRIPTION
**Pull request by ItIsOHM**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Changed the `DefaultBodyLimit` to accept request bodies of size greater than 2 MB

Please explain IN DETAIL what the changes are in this PR and why they are needed:

- Made changes to `HttpOptions` in `src/servers/src/http.rs` and added `DefaultBodyLimit` to the HTTP server layer.

### CODE REVIEW

**Comment by killme2008** [comment]
Thanks, but are u sure the code can be compiled? @ItIsOHM

**Comment by etolbakov** [comment]
Also @ItIsOHM please note that the your branch name doesn't meet the requirements of a feature branch/fix
For details please check:
https://github.com/GreptimeTeam/greptimedb/blob/develop/CONTRIBUTING.md

**Comment by ItIsOHM** [comment]
> Thanks, but are u sure the code can be compiled? @ItIsOHM

I think it should be fine syntactically, but I apologize if there are any errors as I'm a beginner.

I'll run the unit tests and let you know. Can you please tell if I need to update any tests before running them?

**Comment by killme2008** [comment]
@ItIsOHM Please run the test by command line `cargo nextest run --workspace -F pyo3_backend`
Every PR must pass all the test cases and CI actions.
I think you can read the contributing guide first https://github.com/GreptimeTeam/greptimedb/blob/develop/CONTRIBUTING.md

**Comment by ItIsOHM** [comment]
> @ItIsOHM Please run the test by command line `cargo nextest run --workspace -F pyo3_backend` Every PR must pass all the test cases and CI actions. I think you can read the contributing guide first https://github.com/GreptimeTeam/greptimedb/blob/develop/CONTRIBUTING.md

Hey I'm sorry I should've ran the tests before making a PR.

Now that I am running the tests using the command you gave, I'm getting the following error:
image

Can you please help me out and let me know how I can fix them?

**Comment by MichaelScofield** [comment]
@ItIsOHM currently we are working on the build on Windows system. could you use osx or linux?

**Comment by ItIsOHM** [comment]
> @ItIsOHM currently we are working on the build on Windows system. could you use osx or linux?

Ahh I see, unfortunately I'm well versed with using either of those right now. Should I drop this issue for now?

**Comment by killme2008** [comment]
@ItIsOHM Sorry for that. It's fine, take other issues if you are interested. Thank you.

**Pull request closed without merging**
