### PR TITLE
chore: remove redundant code.

### PR DESCRIPTION
**Pull request by DevilExileSu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

+ Remove redundant `len()` and `is_empty()`.
https://github.com/GreptimeTeam/greptimedb/blob/7dbac890002fda25ac6d45adc54df6fceb0ae3d2/src/common/base/src/bytes.rs#L23-L31
+ Remove redundant file [statement_query.rs](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/sql/src/statements/statement_query.rs).

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by evenyag — APPROVED** [review]
LGTM

**Comment by shuiyisong** [comment]
😂 The `len()` and `is_empty()` is not redundant for `Bytes` struct since we wrapped the original `bytes::Bytes` struct and there is no way to access the inner data. 

Maybe adding `#[allow(dead_code)]` would be a good tips here? 😅

**Comment by DevilExileSu** [comment]
> joy The `len()` and `is_empty()` is not redundant for `Bytes` struct since we wrapped the original `bytes::Bytes` struct and there is no way to access the inner data.
> 
> Maybe adding `#[allow(dead_code)]` would be a good tips here? sweat_smile

Sorry, I did not clearly describe it. 

Because `Bytes` implements `Deref`, when you pass the `&Bytes` as a parameter into a function, the implicitly call `deref()` will be performed to get `&bytes::Bytes`.
like this:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c054eb6b0b2f9753aa98f099cbfaccd1

There are more detailed explanations in [rust-book](https://doc.rust-lang.org/book/ch15-02-deref.html) and [rust-doc](https://doc.rust-lang.org/std/ops/trait.Deref.html)

**Review by Fengys123 — APPROVED** [review]
LGTM

**Pull request merged**
