### PR TITLE
chore: bump version to v0.7.0

### PR DESCRIPTION
**Pull request by evenyag**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

- https://github.com/GreptimeTeam/greptimedb/issues/3427

## What's changed and what's your intention?

This PR bumps the db version to v0.7.0.

Wait for #3427 finished.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by evenyag** [comment]
Change the title to avoid someone merging it until blockers in #3427 are resolved.

**Comment by tisonkun** [comment]
We can convert this PR to a draft and update the PR description though.

**Comment by evenyag** [comment]
> We can convert this PR to a draft and update the PR description though.

@tisonkun Then we need to re-run some CI jobs 😢

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Pull request merged**
