### PR TITLE
build(ci): pin linux runner to ubuntu-20.04

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

use `ubuntu-20.04-x` instead of `ubuntu-latest-x`

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by sunng87** [comment]
Interesting, some binaries were cached by 2204 and cannot be used on 2004

**Comment by waynexia** [comment]
> Interesting, some binaries were cached by 2204 and cannot be used on 2004

😵‍💫 Looks like we should manually invalid those caches after this pr

**Review by evenyag — APPROVED** [review]
😢

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Pull request merged**
