### PR TITLE
fix: wrong next column in manifest

### PR DESCRIPTION
**Pull request by lizhemingi**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

fix wrong next column id stored in manifest after adding columns to table.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
#1389

### CODE REVIEW

**Comment by lizhemingi** [comment]
@killme2008 PTAL. And could you please help trigger another sqlness test in CI. It seems failed due to resource issue.

**Comment by killme2008** [comment]
@lizhemingi  I tried restarting the sqlness test twice, but it still failed.  Is it working on your machine?

**Comment by lizhemingi** [comment]
@killme2008 A little wired. I will take a look maybe late tonight or tomorrow morning. And you can take a look on the code for the review if you have time. Thanks.

**Comment by lizhemingi** [comment]
@killme2008 May I ask distributed mode sqlness test support `--- SQLNESS ARG restart=true` or not? I found that remove the restart command in distributed sqlness file passes the test in my local machine. Maybe I thought it's exactly the same test cases between standalone and distributed mode is wrong.

**Comment by killme2008** [comment]
> @killme2008 May I ask distributed mode sqlness test support `--- SQLNESS ARG restart=true` or not? I found that remove the restart command in distributed sqlness file passes the test in my local machine. Maybe I thought it's exactly the same test cases between standalone and distributed mode is wrong.

Ahh, maybe that's the root cause. The distributed mode and standalone mode functions are not totally the same right now. cc @waynexia

**Review by evenyag — APPROVED** [review]
LGTM

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@lizhemingi Thanks a lot. I merged this PR. @waynexia will look into the issue in distribute mode test case.

**Comment by killme2008** [comment]
@lizhemingi The `restart` command can be executed after PR https://github.com/GreptimeTeam/greptimedb/pull/1443

So can you create another PR to test this bug fixing in distributed mode?

**Comment by lizhemingi** [comment]
@killme2008 In #1443, the `alter_table` test case files have been moved into `standalone/common/alter` and in distributed there is a soft link to `standalone/common/alter`. So right now in distributed mode, we will run the same test cases with standalone, and I think it's enough. WDYT ?
image

**Comment by killme2008** [comment]
@lizhemingi Yes, sorry my mistake. @waynexia  already moved it. Great.

**Pull request merged**
