### PR TITLE
feat: add pg create alter table expr translator

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

1. Add alter table expr translator
2. Add create table expr translator

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)
#3174

waits for #3203

### CODE REVIEW

**Comment by zhongzc** [comment]
There is a translator called greptime. Is it the mysql protocol?

**Comment by WenyXu** [comment]
> There is a translator called greptime. Is it the mysql protocol?

I guess it is called a dialect more precisely, instead of a protocol. No matter what we use which protocol in greptime, it always supports the `show create table`, and `desc table` statements.

**Comment by zhongzc** [comment]
> I guess it is called a dialect more precisely, instead of a protocol. No matter what we use which protocol in greptime, it always supports the `show create table`, and `desc table` statements.

I noticed that the translator mod has two submods, one is greptime and the other is postgres. Many of their codes are similar, so I am curious whether there is a dialect of greptime or just MySQL.

**Comment by WenyXu** [comment]
> I noticed that the translator mod has two submods, one is greptime and the other is postgres. Many of their codes are similar, so I am curious whether there is a dialect of greptime or just MySQL.

Good point. I renamed the `greptime` to `mysql`.

**Review by zhongzc — APPROVED** [review]

**Review by fengjiachun — APPROVED** [review]
LGTM

**Pull request merged**
