### PR TITLE
refactor: try to remove unnecessary tests in error mod

### PR DESCRIPTION
**Pull request by waynexia**
Signed-off-by: Ruihang Xia <waynestxia@gmail.com>

I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

We have ignore `error.rs` in codecov's config. This PR tries to remove those (unnecessary) test cases to see if it works. And if so, we don't have to struggle with them anymore 🎉 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@waynexia The ignoring looks like not working at all.

**Comment by waynexia** [comment]
> @waynexia The ignoring looks like not working at all.

Yes, I'm struggling to find out why 🥲

**Comment by waynexia** [comment]
Got the reply from codecov

image

Change this to draft and wait for the reply from codecov.

**Review by fengjiachun — APPROVED** [review]

**Pull request merged**
