### PR TITLE
refactor: split match arms in prom_expr_to_plan into smaller methods

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

No logic changes. Breakdown `prom_expr_to_plan` into several small functions.

Stack size in debug mode after this patch:

Link to the issue for the third time 😣 : https://github.com/rust-lang/rust/issues/34283

## Summary by CodeRabbit

- **Refactor**
  - Improved performance and code organization for PromQL query planning by restructuring logic into separate async functions.

### CODE REVIEW

**Comment by WenyXu** [comment]
It works on my machine🤩
Before
```
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 148304
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96
Function: query::promql::planner::{impl#1}::stmt_to_plan::{async_fn#0}, Stack Size: 1760
```
After this PR:
```
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 17
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 18
Function: query::promql::planner::{impl#1}::prom_call_expr_to_plan::{async_fn#0}, Stack Size: 21488, i: 19
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 20
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 21
Function: query::promql::planner::{impl#1}::prom_aggr_expr_to_plan::{async_fn#0}, Stack Size: 11952, i: 22
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 23
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 24
Function: query::promql::planner::{impl#1}::prom_binary_expr_to_plan::{async_fn#0}, Stack Size: 31360, i: 25
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 26
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 27
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 28
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 29
Function: query::promql::planner::{impl#1}::prom_binary_expr_to_plan::{async_fn#0}, Stack Size: 31360, i: 30
Function: query::promql::planner::{impl#1}::prom_expr_to_plan::{async_block#0}, Stack Size: 37552, i: 31
Function: core::future::future::{impl#1}::poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<datafusion_expr::logical_plan::plan::LogicalPlan, query::promql::error::Error>> + core::marker::Send), alloc::alloc::Global>>, Stack Size: 96, i: 32
Function: query::promql::planner::{impl#1}::stmt_to_plan::{async_fn#0}, Stack Size: 1760, i: 33
```

**Review by WenyXu — APPROVED** [review]

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by discord9 — APPROVED** [review]
DLJB

**Comment by waynexia** [comment]
The script to compute stack size: https://wiki.waynest.com/#/page/gdb%20compute%20stack%20size

**Pull request merged**
