### PR TITLE
feat: benchmark table metadata managers

### LINKED ISSUE #2001: Table metadata desgin document and micro benchmark
### What type of enhancement is this?

Performance, Tech debt reduction

### What does the enhancement do?

After #1985 , we successfully refactored the table metadata in distributed mode, but missed some performance microbenchmarks and the design document, especially the metadata key format.

Let us do these jobs ASAP.

The microbenchmarks of table metadata operations may give us some insights into the potential performance bottleneck and help to resolve them.

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by MichaelScofield**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Benchmark newly added 4 table metadata managers against Etcd store.

Some results:

In my localhost, one etcd server:

each table metadata key type with 1000 keys:

```txt
./greptime cli bench --etcd-addr=127.0.0.1:2379 --count=1000

2023-07-20T12:17:13.651772Z  INFO greptime: short_version: 0.3.2, full_version: greptimedb-develop-6235441
2023-07-20T12:17:13.651810Z  INFO greptime: command line arguments
2023-07-20T12:17:13.651814Z  INFO greptime: argument: ./greptime
2023-07-20T12:17:13.651818Z  INFO greptime: argument: cli
2023-07-20T12:17:13.651820Z  INFO greptime: argument: bench
2023-07-20T12:17:13.651822Z  INFO greptime: argument: --etcd-addr=127.0.0.1:2379
2023-07-20T12:17:13.651825Z  INFO greptime: argument: --count=1000
2023-07-20T12:17:13.651959Z  INFO cmd::cli::bench: Start benching table name manager ...
2023-07-20T12:17:19.063033Z  INFO cmd::cli::bench: TableNameBencher: create 1000 table names, average operation cost: 5.41 ms
2023-07-20T12:17:25.416368Z  INFO cmd::cli::bench: TableNameBencher: rename 1000 table names, average operation cost: 6.35 ms
2023-07-20T12:17:25.567181Z  INFO cmd::cli::bench: TableNameBencher: get 1000 table names, average operation cost: 0.15 ms
2023-07-20T12:17:30.989503Z  INFO cmd::cli::bench: TableNameBencher: list all 1000 table names, average operation cost: 5.42 ms
2023-07-20T12:17:37.296412Z  INFO cmd::cli::bench: TableNameBencher: remove 1000 table names, average operation cost: 6.31 ms
2023-07-20T12:17:37.296562Z  INFO cmd::cli::bench: Start benching table info manager ...
2023-07-20T12:17:43.221760Z  INFO cmd::cli::bench: TableInfoBencher: create 1000 table infos, average operation cost: 5.92 ms
2023-07-20T12:17:43.395957Z  INFO cmd::cli::bench: TableInfoBencher: get 1000 table infos, average operation cost: 0.17 ms
2023-07-20T12:17:50.857900Z  INFO cmd::cli::bench: TableInfoBencher: compare_and_put 1000 table infos, average operation cost: 1.68 ms
2023-07-20T12:17:58.090063Z  INFO cmd::cli::bench: TableInfoBencher: remove 1000 table infos, average operation cost: 7.23 ms
2023-07-20T12:17:58.090206Z  INFO cmd::cli::bench: Start benching table region manager ...
2023-07-20T12:18:03.682165Z  INFO cmd::cli::bench: TableRegionBencher: create 1000 table regions, average operation cost: 5.57 ms
2023-07-20T12:18:03.818405Z  INFO cmd::cli::bench: TableRegionBencher: get 1000 table regions, average operation cost: 0.14 ms
2023-07-20T12:18:10.382177Z  INFO cmd::cli::bench: TableRegionBencher: compare_and_put 1000 table regions, average operation cost: 1.17 ms
2023-07-20T12:18:17.018303Z  INFO cmd::cli::bench: TableRegionBencher: remove 1000 table regions, average operation cost: 6.63 ms
2023-07-20T12:18:17.019046Z  INFO cmd::cli::bench: Start benching datanode table manager ...
2023-07-20T12:18:22.763439Z  INFO cmd::cli::bench: DatanodeTableBencher: create 1000 datanode table keys, average operation cost: 5.74 ms
2023-07-20T12:18:22.904182Z  INFO cmd::cli::bench: DatanodeTableBencher: get 1000 datanode table keys, average operation cost: 0.14 ms
2023-07-20T12:18:29.249815Z  INFO cmd::cli::bench: DatanodeTableBencher: move 1000 datanode table regions, average operation cost: 6.34 ms
2023-07-20T12:18:34.454797Z  INFO cmd::cli::bench: DatanodeTableBencher: list 1000 datanode table keys, average operation cost: 5.20 ms
2023-07-20T12:18:40.637737Z  INFO cmd::cli::bench: DatanodeTableBencher: remove 1000 datanode table keys, average operation cost: 6.18 ms
```

each table metadata key type with 2000 keys:

```txt
./greptime cli bench --etcd-addr=127.0.0.1:2379 --count=2000

2023-07-20T12:20:02.533314Z  INFO greptime: short_version: 0.3.2, full_version: greptimedb-develop-6235441
2023-07-20T12:20:02.533353Z  INFO greptime: command line arguments
2023-07-20T12:20:02.533358Z  INFO greptime: argument: ./greptime
2023-07-20T12:20:02.533362Z  INFO greptime: argument: cli
2023-07-20T12:20:02.533364Z  INFO greptime: argument: bench
2023-07-20T12:20:02.533366Z  INFO greptime: argument: --etcd-addr=127.0.0.1:2379
2023-07-20T12:20:02.533369Z  INFO greptime: argument: --count=2000
2023-07-20T12:20:02.533497Z  INFO cmd::cli::bench: Start benching table name manager ...
2023-07-20T12:20:13.868834Z  INFO cmd::cli::bench: TableNameBencher: create 2000 table names, average operation cost: 5.67 ms
2023-07-20T12:20:26.784701Z  INFO cmd::cli::bench: TableNameBencher: rename 2000 table names, average operation cost: 6.46 ms
2023-07-20T12:20:27.013861Z  INFO cmd::cli::bench: TableNameBencher: get 2000 table names, average operation cost: 0.11 ms
2023-07-20T12:20:47.934222Z  INFO cmd::cli::bench: TableNameBencher: list all 2000 table names, average operation cost: 10.46 ms
2023-07-20T12:21:00.968669Z  INFO cmd::cli::bench: TableNameBencher: remove 2000 table names, average operation cost: 6.52 ms
2023-07-20T12:21:00.968821Z  INFO cmd::cli::bench: Start benching table info manager ...
2023-07-20T12:21:13.995225Z  INFO cmd::cli::bench: TableInfoBencher: create 2000 table infos, average operation cost: 6.51 ms
2023-07-20T12:21:14.317976Z  INFO cmd::cli::bench: TableInfoBencher: get 2000 table infos, average operation cost: 0.16 ms
2023-07-20T12:21:31.044143Z  INFO cmd::cli::bench: TableInfoBencher: compare_and_put 2000 table infos, average operation cost: 2.00 ms
2023-07-20T12:21:46.716813Z  INFO cmd::cli::bench: TableInfoBencher: remove 2000 table infos, average operation cost: 7.84 ms
2023-07-20T12:21:46.717295Z  INFO cmd::cli::bench: Start benching table region manager ...
2023-07-20T12:21:58.135672Z  INFO cmd::cli::bench: TableRegionBencher: create 2000 table regions, average operation cost: 5.69 ms
2023-07-20T12:21:58.365583Z  INFO cmd::cli::bench: TableRegionBencher: get 2000 table regions, average operation cost: 0.11 ms
2023-07-20T12:22:11.130610Z  INFO cmd::cli::bench: TableRegionBencher: compare_and_put 2000 table regions, average operation cost: 1.35 ms
2023-07-20T12:22:23.723357Z  INFO cmd::cli::bench: TableRegionBencher: remove 2000 table regions, average operation cost: 6.30 ms
2023-07-20T12:22:23.723499Z  INFO cmd::cli::bench: Start benching datanode table manager ...
2023-07-20T12:22:34.879724Z  INFO cmd::cli::bench: DatanodeTableBencher: create 2000 datanode table keys, average operation cost: 5.58 ms
2023-07-20T12:22:35.087332Z  INFO cmd::cli::bench: DatanodeTableBencher: get 2000 datanode table keys, average operation cost: 0.10 ms
2023-07-20T12:22:48.392185Z  INFO cmd::cli::bench: DatanodeTableBencher: move 2000 datanode table regions, average operation cost: 6.65 ms
2023-07-20T12:22:59.319960Z  INFO cmd::cli::bench: DatanodeTableBencher: list 2000 datanode table keys, average operation cost: 5.46 ms
2023-07-20T12:23:11.775559Z  INFO cmd::cli::bench: DatanodeTableBencher: remove 2000 datanode table keys, average operation cost: 6.23 ms
```

each table metadata key type with 5000 keys:

```txt
./greptime cli bench --etcd-addr=127.0.0.1:2379 --count=5000

2023-07-20T12:31:01.305068Z  INFO greptime: short_version: 0.3.2, full_version: greptimedb-develop-6235441
2023-07-20T12:31:01.305152Z  INFO greptime: command line arguments
2023-07-20T12:31:01.305157Z  INFO greptime: argument: ./greptime
2023-07-20T12:31:01.305162Z  INFO greptime: argument: cli
2023-07-20T12:31:01.305164Z  INFO greptime: argument: bench
2023-07-20T12:31:01.305167Z  INFO greptime: argument: --etcd-addr=127.0.0.1:2379
2023-07-20T12:31:01.305169Z  INFO greptime: argument: --count=5000
2023-07-20T12:31:01.305637Z  INFO cmd::cli::bench: Start benching table name manager ...
2023-07-20T12:31:29.620964Z  INFO cmd::cli::bench: TableNameBencher: create 5000 table names, average operation cost: 5.66 ms
2023-07-20T12:32:04.070260Z  INFO cmd::cli::bench: TableNameBencher: rename 5000 table names, average operation cost: 6.89 ms
2023-07-20T12:32:04.543397Z  INFO cmd::cli::bench: TableNameBencher: get 5000 table names, average operation cost: 0.09 ms
2023-07-20T12:33:01.757599Z  INFO cmd::cli::bench: TableNameBencher: list all 5000 table names, average operation cost: 11.44 ms
2023-07-20T12:33:33.118271Z  INFO cmd::cli::bench: TableNameBencher: remove 5000 table names, average operation cost: 6.27 ms
2023-07-20T12:33:33.118299Z  INFO cmd::cli::bench: Start benching table info manager ...
2023-07-20T12:34:02.278699Z  INFO cmd::cli::bench: TableInfoBencher: create 5000 table infos, average operation cost: 5.83 ms
2023-07-20T12:34:02.914715Z  INFO cmd::cli::bench: TableInfoBencher: get 5000 table infos, average operation cost: 0.13 ms
2023-07-20T12:34:39.994331Z  INFO cmd::cli::bench: TableInfoBencher: compare_and_put 5000 table infos, average operation cost: 1.63 ms
2023-07-20T12:35:15.771803Z  INFO cmd::cli::bench: TableInfoBencher: remove 5000 table infos, average operation cost: 7.16 ms
2023-07-20T12:35:15.771873Z  INFO cmd::cli::bench: Start benching table region manager ...
2023-07-20T12:35:43.620144Z  INFO cmd::cli::bench: TableRegionBencher: create 5000 table regions, average operation cost: 5.56 ms
2023-07-20T12:35:44.138244Z  INFO cmd::cli::bench: TableRegionBencher: get 5000 table regions, average operation cost: 0.10 ms
2023-07-20T12:36:18.966310Z  INFO cmd::cli::bench: TableRegionBencher: compare_and_put 5000 table regions, average operation cost: 1.50 ms
2023-07-20T12:36:52.422921Z  INFO cmd::cli::bench: TableRegionBencher: remove 5000 table regions, average operation cost: 6.69 ms
2023-07-20T12:36:52.423058Z  INFO cmd::cli::bench: Start benching datanode table manager ...
2023-07-20T12:37:20.716664Z  INFO cmd::cli::bench: DatanodeTableBencher: create 5000 datanode table keys, average operation cost: 5.66 ms
2023-07-20T12:37:21.181863Z  INFO cmd::cli::bench: DatanodeTableBencher: get 5000 datanode table keys, average operation cost: 0.09 ms
2023-07-20T12:37:55.329435Z  INFO cmd::cli::bench: DatanodeTableBencher: move 5000 datanode table regions, average operation cost: 6.83 ms
2023-07-20T12:38:40.907561Z  INFO cmd::cli::bench: DatanodeTableBencher: list 5000 datanode table keys, average operation cost: 9.12 ms
2023-07-20T12:39:13.583275Z  INFO cmd::cli::bench: DatanodeTableBencher: remove 5000 datanode table keys, average operation cost: 6.54 ms
```

Will try to run same benchmark in our cloud env.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
close #2001

### CODE REVIEW

**Comment by MichaelScofield** [comment]
etcd's own performance benchmark is [here](https://etcd.io/docs/v3.5/op-guide/performance/)

**Comment by WenyXu** [comment]
Three major problems: 
1. We need to simulate the production environment key name as possible.
2. Lacks a benchmark run in parallel.
3. Lacks a benchmark comparing the performance of many small transactions with a large transaction.

I add the [benchmark run in parallel](https://github.com/WenyXu/greptimedb/tree/feat/bench-table-metadata-weny) and found poor performance. 

The environment is i9 13900k, 96GB DDR4 3200, Single Etcd.

Parallel bench
```
2023-07-20T16:15:12.750026Z  INFO cmd::cli::bench: Start benching table name manager ...
2023-07-20T16:15:13.361792Z  INFO cmd::cli::bench::table_name: TableNameBencher: create 5000 table names, average operation cost: 305 ms, p50: 304 ms, p95: 570 ms, p99: 597 ms
2023-07-20T16:15:14.545888Z  INFO cmd::cli::bench::table_name: TableNameBencher: rename 5000 table names, average operation cost: 851 ms, p50: 859 ms, p95: 1136 ms, p99: 1161 ms
2023-07-20T16:15:15.047750Z  INFO cmd::cli::bench::table_name: TableNameBencher: get 5000 table names, average operation cost: 245 ms, p50: 243 ms, p95: 463 ms, p99: 486 ms
2023-07-20T16:15:50.871026Z  INFO cmd::cli::bench::table_name: TableNameBencher: list all 5000 table names, average operation cost: 21182 ms, p50: 21420 ms, p95: 34367 ms, p99: 35528 ms
2023-07-20T16:15:52.115593Z  INFO cmd::cli::bench::table_name: TableNameBencher: remove 5000 table names, average operation cost: 916 ms, p50: 918 ms, p95: 1203 ms, p99: 1228 ms
```

Serial bench (Although not the benchmark for same key)
```
2023-07-20T16:15:52.115703Z  INFO cmd::cli::bench: Start benching table info manager ...
2023-07-20T16:16:02.434534Z  INFO cmd::cli::bench: TableInfoBencher: create 5000 table infos, average operation cost: 2.06 ms
2023-07-20T16:16:04.377175Z  INFO cmd::cli::bench: TableInfoBencher: get 5000 table infos, average operation cost: 0.39 ms
2023-07-20T16:16:16.240116Z  INFO cmd::cli::bench: TableInfoBencher: compare_and_put 5000 table infos, average operation cost: 0.87 ms
2023-07-20T16:16:26.826313Z  INFO cmd::cli::bench: TableInfoBencher: remove 5000 table infos, average operation cost: 2.12 ms
```

**Comment by WenyXu** [comment]
BTW, The official benchmark tool shares the connections between the clients. This is different in our environment, considering scaling up to 100 or 1000 clients to run above the benchmark again.

Screenshot 2023-07-21 at 1 50 26

https://github.com/etcd-io/etcd/blob/92de641a228d5be32177bf7eb9d3711f9453ef36/tools/benchmark/cmd/util.go#L138-L149
```go
func mustCreateClients(totalClients, totalConns uint) []*clientv3.Client {
	conns := make([]*clientv3.Client, totalConns)
	for i := range conns {
		conns[i] = mustCreateConn()
	}

	clients := make([]*clientv3.Client, totalClients)
	for i := range clients {
		clients[i] = conns[i%int(totalConns)]
	}
	return clients
}

```

**Comment by WenyXu** [comment]
I added a benchmark to compare small transactions with a single large transaction at [here](https://github.com/WenyXu/greptimedb/tree/feat/bench-table-metadata-large-txn-weny).

#### 1 Client 100 Parallel
```
2023-07-20T17:34:31.029051Z  INFO cmd::cli::bench: Start benching table metadata with small transactions ...
2023-07-20T17:34:31.084079Z  INFO cmd::cli::bench::table_meta: TableMetadata: create 100 table metadata, average operation cost: 48 ms, p50: 48 ms, p95: 54 ms, p99: 54 ms
2023-07-20T17:34:31.084161Z  INFO cmd::cli::bench: Start benching table metadata with single large transaction ...
2023-07-20T17:34:31.100381Z  INFO cmd::cli::bench::table_meta: TableMetadata with large txn: create 100 table metadata, average operation cost: 8 ms, p50: 8 ms, p95: 14 ms, p99: 14 ms
```

#### 1 Client 1000 Parallel
```
2023-07-20T17:38:07.186186Z  INFO cmd::cli::bench: Start benching table metadata with small transactions ...
2023-07-20T17:38:07.717675Z  INFO cmd::cli::bench::table_meta: TableMetadata: create 1000 table metadata, average operation cost: 464 ms, p50: 463 ms, p95: 518 ms, p99: 522 ms
2023-07-20T17:38:07.717770Z  INFO cmd::cli::bench: Start benching table metadata with single large transaction ...
2023-07-20T17:38:07.863692Z  INFO cmd::cli::bench::table_meta: TableMetadata with large txn: create 1000 table metadata, average operation cost: 75 ms, p50: 75 ms, p95: 125 ms, p99: 130 ms
```
#### 1 Client 5000 Parallel
```
2023-07-20T17:38:41.516714Z  INFO cmd::cli::bench: Start benching table metadata with small transactions ...
2023-07-20T17:38:44.182877Z  INFO cmd::cli::bench::table_meta: TableMetadata: create 5000 table metadata, average operation cost: 2330 ms, p50: 2329 ms, p95: 2621 ms, p99: 2646 ms
2023-07-20T17:38:44.182991Z  INFO cmd::cli::bench: Start benching table metadata with single large transaction ...
2023-07-20T17:38:44.958529Z  INFO cmd::cli::bench::table_meta: TableMetadata with large txn: create 5000 table metadata, average operation cost: 382 ms, p50: 382 ms, p95: 667 ms, p99: 693 ms
```

However, this bench still runs with a single etcd, and It doesn't encounter network overhead of log replication.

**Comment by MichaelScofield** [comment]
@WenyXu We are benching our table metadata operation's latency, not the etcd, is it necessary to use multiple clients here? I think latency and throughput are two different aspects of benchmark here. Latency answers the question "how long does it take to accomplish the this specific table metadata operation?", and throughput answers "how many table metadata operations can be done in a length of time". We are actually more care about the latency here, because the throughput must be taken into account in a bigger picture to make it meaningful to us. For example, it's more meaningful to say "the metasrv can finish 1000 region failover procedures in a second", than to say "the update table metadata step in region failover procedure can be done 2000 times in a second".

**Comment by MichaelScofield** [comment]
@WenyXu @fengjiachun about the txn api design, I'd prefer not to expose the `txn` object out. Table metadata management is very critical, should be treated with extreme care. Make txn escape the scope of table metadata manager is like the `unsafe` rust. On the other hand, the places to use txn is (and should be) limited. So it's better to write functions for each use case of txn in `TableMetadataManager`.

**Review by fengjiachun — APPROVED** [review]

**Comment by fengjiachun** [comment]
> @WenyXu @fengjiachun about the txn api design, I'd prefer not to expose the `txn` object out. Table metadata management is very critical, should be treated with extreme care. Make txn escape the scope of table metadata manager is like the `unsafe` rust. On the other hand, the places to use txn is (and should be) limited. So it's better to write functions for each use case of txn in `TableMetadataManager`.

I understand your worries.
When we haven't really encountered a performance bottleneck, we can keep the status quo. Merging txn is just a way to optimize performance.
We can consider it when we actually encounter performance issues. WDYT @WenyXu

**Review by WenyXu — APPROVED** [review]

**Comment by MichaelScofield** [comment]
update: I've done the same benchmark in our cloud env, [results](https://greptime.feishu.cn/wiki/KCavw2n5KiDehKkq0aKckKhcnVh)

**Pull request merged**
