### PR TITLE
refactor!: remove duration type from gRPC

### LINKED ISSUE #3230: Cannot show-table with Duration Type
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

1. Use the SDK to write data of type Duration, which will trigger automatic table creation in the database.
2. Execute `SHOW CREATE TABLE`, then get a panic.

In fact, the reason is that there is a lack of mapping from the Duration type to the SQL type [here](https://github.com/GreptimeTeam/greptimedb/blob/main/src/sql/src/statements.rs#L504).

### What did you expect to see?

//

### What did you see instead?

//

### What operating system did you use?

Mac OS X 10.5 ARM

### What version of GreptimeDB did you use?

0.6.0

### Relevant log output and stack trace

_No response_

### PR DESCRIPTION
**Pull request by fengjiachun**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

As the title said.

https://github.com/GreptimeTeam/greptime-proto/pull/158

close #3230 

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by tisonkun** [comment]
This should be related or closes https://github.com/GreptimeTeam/greptimedb/issues/3230.

**Comment by fengjiachun** [comment]
Waiting for: https://github.com/GreptimeTeam/greptime-proto/pull/158

**Comment by fengjiachun** [comment]
> Waiting for: [GreptimeTeam/greptime-proto#158](https://github.com/GreptimeTeam/greptime-proto/pull/158)

Done

**Review by tisonkun — APPROVED** [review]

**Review by killme2008 — APPROVED** [review]
LGTM

**Pull request merged**
