### PR TITLE
fix: cast orc data against output schema 

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Cast orc data against output schema

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
LGTM

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Comment by waynexia** [comment]
Looks like we haven't covered ORC format in sqlness

**Comment by WenyXu** [comment]
> Looks like we haven't covered ORC format in sqlness

Create an issue and label it a `Good first issue` 😇

**Pull request merged**
