### PR TITLE
feat: initial implement for promql subquery

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Support query like `avg by (job) (avg_over_time((up <= 50)[5s:5s]))`

This PR only handles range and step in subquery. Other parameters are ignored.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
- #1042

### CODE REVIEW

**Review by killme2008 — COMMENTED** [review]
Good job! But i think we should add some test cases for this feature.

**Comment by waynexia** [comment]
> Good job! But i think we should add some test cases for this feature.

Test cases in prometheus are a little complicated. I'm going to make a new sqlness interceptor for them.

**Comment by killme2008** [comment]
@waynexia Don't forget this PR. 👍

**Comment by waynexia** [comment]
> @waynexia Don't forget this PR. 👍

Waiting for https://github.com/CeresDB/sqlness/issues/51

**Comment by tisonkun** [comment]
@waynexia as you know the sqlness blocker is unblocked. Reminder for this issue :D

**Comment by tisonkun** [comment]
Close as stale. This changeset is small. I suppose when we'd like to pick it up, we can open a new PR.

**Pull request closed without merging**
