### PR TITLE
chore: ignore MySQL client sent SELECT $$

### PR DESCRIPTION
**Pull request by tisonkun**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This closes https://github.com/GreptimeTeam/greptimedb/issues/2514.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by WenyXu — APPROVED** [review]
Thank @tisonkun, Almost LGTM. Maybe it's better to add a simple sqlness for this case, If you don't mind ❤️

**Comment by tisonkun** [comment]
@WenyXu Thanks for your review! This patch is active for MySQL interface only. I try sqlness case locally but it doesn't seem go through the MySQL server logic.

Is there other proper place to write IT cases?

**Comment by WenyXu** [comment]
> @WenyXu Thanks for your review! This patch is active for MySQL interface only. I try sqlness case locally but it doesn't seem go through the MySQL server logic.
> 
> Is there other proper place to write IT cases?

Oh, My bad. You reminded me that our sqlness is using the gRPC protocol. Let's go ahead and leave this IT case as future work.

**Review by QuenKar — APPROVED** [review]
LGTM

**Pull request merged**
