### PR TITLE
docs: rfc of refactoring table trait

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

RFC of refactoring the table trait.

[rendered](https://github.com/waynexia/greptimedb/blob/rfc-table-abstract/docs/rfcs/2023-08-04-tabie-trait-refactor.md)

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
#2065

### CODE REVIEW

**Review by killme2008 — APPROVED** [review]
Looks much more clear and better.

**Comment by waynexia** [comment]
> The `scan_to_stream` is kind of confused. Why not just the `scan`. The stream should be the first-class citizen.

There was a `scan()`, which doesn't return `RecordBatchStream` but `PhysicalPlan` instead. The `scan_to_stream()` is introduced in https://github.com/GreptimeTeam/greptimedb/pull/1639, there was a time that both methods existed and this is why it has a weird name

**Review by fengjiachun — APPROVED** [review]
LGTM

**Review by evenyag — APPROVED** [review]
Let's have a try and let the compiler teach us

**Pull request merged**
