### PR TITLE
feat!: do not get TZ info from server local env

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Remove the logic of fetching server's local timezone as the default timezone. Use Zulu (UTC+0) by default. We can provide a method to set per-session timezone in the future, as requested in https://github.com/GreptimeTeam/greptimedb/issues/2893

> [!WARNING]
> This is a breaking change. After this patch, the server-side timezone will default to GMT instead of environment `$TZ`. It would be configurable in the future (#2907)

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
Closes https://github.com/GreptimeTeam/greptimedb/issues/2856
Part of #2907

### CODE REVIEW

**Comment by killme2008** [comment]
@waynexia Is this a breaking change?

**Comment by waynexia** [comment]
> @waynexia Is this a breaking change?

Yes, I've changed the title

**Review by MichaelScofield — APPROVED** [review]

**Comment by MichaelScofield** [comment]
A user says he's using Influxdb line protocol with explicit timestamp to write, and read with timestamp (instead of the date time like "2023-12-12 17:45:00"). So I think this breaking change is fine.

**Review by killme2008 — APPROVED** [review]

**Comment by killme2008** [comment]
Let's move on!

**Pull request merged**
