### PR TITLE
feat: type alias

### LINKED ISSUE #2294: Use the same GreptimeDB datatype in "CREATE TABLE" and "DESC TABLE"
### What type of enhancement is this?

API improvement

### What does the enhancement do?

The data types in "CREATE TABLE" and "DESC TABLE" are different which confuses users, for example:

```sql
CREATE TABLE data_types (
  s string,
  tint tinyint,
  sint smallint,
  i int,
  bint bigint,
  v varchar,
  f float,
  d double,
  b boolean,
  vb varbinary,
  dt date,
  dtt datetime,
  ts0 timestamp(0),
  ts3 timestamp(3),
  ts6 timestamp(6),
  ts9 timestamp(9) DEFAULT CURRENT_TIMESTAMP TIME INDEX,
  PRIMARY KEY(s));
```

```sql
+--------+----------------------+------+------+---------------------+---------------+
| Column | Type                 | Key  | Null | Default             | Semantic Type |
+--------+----------------------+------+------+---------------------+---------------+
| s      | String               | PRI  | YES  |                     | TAG           |
| tint   | Int8                 |      | YES  |                     | FIELD         |
| sint   | Int16                |      | YES  |                     | FIELD         |
| i      | Int32                |      | YES  |                     | FIELD         |
| bint   | Int64                |      | YES  |                     | FIELD         |
| v      | String               |      | YES  |                     | FIELD         |
| f      | Float32              |      | YES  |                     | FIELD         |
| d      | Float64              |      | YES  |                     | FIELD         |
| b      | Boolean              |      | YES  |                     | FIELD         |
| vb     | Binary               |      | YES  |                     | FIELD         |
| dt     | Date                 |      | YES  |                     | FIELD         |
| dtt    | DateTime             |      | YES  |                     | FIELD         |
| ts0    | TimestampSecond      |      | YES  |                     | FIELD         |
| ts3    | TimestampMillisecond |      | YES  |                     | FIELD         |
| ts6    | TimestampMicrosecond |      | YES  |                     | FIELD         |
| ts9    | TimestampNanosecond  | PRI  | NO   | current_timestamp() | TIMESTAMP     |
+--------+----------------------+------+------+---------------------+---------------+
16 rows in set (0.00 sec)
```

It is hoped that `CREATE TABLE` can use the same data type as `DESC TABLE`, such as Int32, Float32, TimestampSecond...

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by killme2008**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Try to fix #2294 #2072 

Main changes:

* Adds `transform` mod to statements. It is using to transform statements by rules.
* Supports sql data type alias:
    * `TimestampSecond`, `Timestamp_s`, `Timestamp_sec` for `Timestamp(0)`.
    * `TimestampMillisecond`, `Timestamp_ms` for `Timestamp(3)`.
    * `TimestampMicrosecond`, `Timestamp_us` for `Timestamp(6)`.
    * `TimestampNanosecond`, `Timestamp_ns` for `Timestamp(9)`.
    * `INT8` for `tinyint`
    * `INT16` for `smallint`
    * `INT32` for `int`
    * `INT32` for `bigint`
    *  And `UINT8`, `UINT16` etc. for `UnsignedTinyint` etc.
* Fixed lots of timestamp test cases and adds `timestamp_types.sql` to test timestamp types

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
#2294 #2072

### CODE REVIEW

**Comment by killme2008** [comment]
@waynexia @v0y4g3r Please take a look when you are free.

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@waynexia PTAL

**Review by zhongzc — APPROVED** [review]
LGTM 👍

**Comment by fengjiachun** [comment]
@killme2008  There are some conflicts.

**Review by waynexia — APPROVED** [review]
🚀

**Pull request merged**
