### PR TITLE
refactor!: remove opentsdb tcp server

### PR DESCRIPTION
**Pull request by shuiyisong**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

This pr mainly removes the OpenTSDB TCP server, for 
1. it's the only protocol on raw TCP layer, which brings a lot of feature implementation differences and difficulties compared to other server.
2. we suspect that not many users use the TCP protocol for ingesting OpenTSDB data. Users can still use the HTTP endpoint for OpenTSDB data ingestion.

We have not yet reached a final agreement. Please leave comments below if you have opposite opinion.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [ ]  This PR does not require documentation updates.

### CODE REVIEW

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by shuiyisong** [comment]
> Do we have some docs to update after this PR merged?

Yes, I'll check the doc once this pr is merged.

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
> We have not yet reached a final agreement. Please leave comments below if you have opposite opinion.

I just saw this. Sorry.

**Comment by shuiyisong** [comment]
Now the `opentsdb_addr` is removed from start command in both frontend and standalone. Related configs and docs are modified. PTAL @tisonkun

**Pull request merged**
