### PR TITLE
chore: deprecate nyc-taxi benchmark

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

Remove `nyc-taxi-bench`. It's not used for a long time. We now have other professional tools to do benchmarks.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
> We now have other professional tools to do benchmarks

What is it?

**Comment by waynexia** [comment]
> > We now have other professional tools to do benchmarks
> 
> What is it?

https://github.com/GreptimeTeam/greptimedb/tree/main/docs/benchmarks/tsbs

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by fengjiachun** [comment]
We also to remove the docs: https://docs.greptime.com/contributor-guide/benchmarks/nyc-taxi#nyc-taxi-benchmark

**Pull request merged**
