### PR TITLE
feat: do not require worker's number to be power of 2

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This patch changes the default number of mito workers from 1 to the half of CPU number.

And remove the constraint that the worker's number has to be the power of two. As the number of CPUs cannot even be even these days 

image

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by WenyXu — APPROVED** [review]
M1 Max says it still can work three years😤

**Comment by killme2008** [comment]
So what's the reason to change this default value? Sorry, i don't find any explanation in the PR.

**Comment by waynexia** [comment]
> So what's the reason to change this default value? Sorry, i don't find any explanation in the PR.

1 is too small. It's not a good default value

**Comment by fengjiachun** [comment]
Why is it num_cpus/2 instead of num_cpus?

**Comment by waynexia** [comment]
> Why is it num_cpus/2 instead of num_cpus?

Leave some resources to query, other engines and other background jobs

**Review by fengjiachun — APPROVED** [review]

**Pull request merged**
