### PR TITLE
refactor: avoid unnecessary alloc by using unwrap_or_else

### PR DESCRIPTION
**Pull request by etolbakov**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
https://github.com/GreptimeTeam/greptimedb/issues/3453
https://github.com/GreptimeTeam/greptimedb/pull/3630

## What's changed and what's your intention?
improve the implementation by avoid an allocation if the lookback value is provided.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by etolbakov** [comment]
@killme2008 @waynexia @tisonkun 
Could you please take a look when you have time?

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Thank you!

**Comment by tisonkun** [comment]
I update the PR title. We're now generating release notes from PR title, so keeping it clear and expressive is important :D

**Review by fengjiachun — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
