### PR TITLE
ci: download the latest stable released version by default and do some small refactoring

### PR DESCRIPTION
**Pull request by zyy17**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

1. Download the latest stable released version by default;
2. Do some small refactoring:

   - Add `GITHUB_TOKEN`;
   - Code format;
   - Add `download_artifact()`;
   
## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by sunng87 — APPROVED** [review]

**Comment by sunng87** [comment]
Actually if we are downloading artifacts from the latest release, it doesn't need to call Github api to find out exact version number, just use url like this one:

https://github.com/GreptimeTeam/greptimedb/releases/latest/download/greptime-linux-amd64-centos-v0.9.1.tar.gz

**Comment by zyy17** [comment]
> Actually if we are downloading artifacts from the latest release, it doesn't need to call Github api to find out exact version number, just use url like this one:
> 
> https://github.com/GreptimeTeam/greptimedb/releases/latest/download/greptime-linux-amd64-centos-v0.9.1.tar.gz

Yeap, I know the usage. However, you still need to know the specified version to download the package.

**Comment by sunng87** [comment]
I see. We have version number on the file name

**Pull request merged**
