### PR TITLE
feat: enable azblob tests

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Enable azblob tests

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by WenyXu** [comment]
@ v0y4g3r I also fixed a missing argument issue, which caused the CI to fail.

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Comment by v0y4g3r** [comment]
> @ v0y4g3r I tried to fix a missing argument issue, which caused the CI to fail. However, it seems we still have other issues.🥲

It's seems to relate to some lifetime issue of `Arc` wrapped structs have not been dropped.

**Review by fengjiachun — APPROVED** [review]
LGTM

**Pull request merged**
