### PR TITLE
feat: support rename table

### LINKED ISSUE #723: Tracking Issue: Supports rename table
### What type of enhancement is this?

API improvement

### What does the enhancement do?

As discussed in #660 , we decide to using table id as the table data path  to support `RENAME TABLE`. This issue tracks the progress of this work.

### Implementation challenges

This feature will be implemented in the following steps:
- [x] change the table path to schema/table_id #728 
- [x] support renaming tables in the mito table engine, this may require to #802 
  - persist the change to manifest (maybe a new MetaAction is required)
  - change the in-memory metadata
  - recover the change when reopening the table
- [x] support renaming tables for the catalog manager in standalone mode #824 
  - update the catalog's metadata
- [ ] support rename table in distribute mode
- [x] support parsing the RENAME TABLE statements in the parser and execute the rename statement #780

### PR DESCRIPTION
**Pull request by e1ijah1**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

support parsing the RENAME TABLE statements in the parser and execute the rename statement

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

closes #723

### CODE REVIEW

**Comment by e1ijah1** [comment]
It looks like there may be some issue with CI. PTAL
cc @killme2008 @evenyag @waynexia

**Comment by evenyag** [comment]
> It looks like there may be some issue with CI.

You could click the details to see which test failed.

```
--- STDERR:                   catalog::remote_catalog_tests tests::test_rename_table ---
thread 'tests::test_rename_table' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyValue { backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/backtrace_shim.rs:15:19
      <catalog::error::EmptyValueSnafu>::build
             at src/error.rs:24:17
   1: <catalog::error::EmptyValueSnafu>::fail::<bool>
             at src/error.rs:24:17
   2: <catalog::remote::manager::RemoteCatalogManager as catalog::CatalogManager>::rename_table::{closure#0}
             at src/remote/manager.rs:470:24
   3: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<bool, catalog::error::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
   4: remote_catalog_tests::tests::test_rename_table::{closure#0}
             at tests/remote_catalog_tests.rs:296:13
```

**Comment by evenyag** [comment]
> It looks like there may be some issue with CI.

You could click the details to see which test failed.

```
--- STDERR:                   catalog::remote_catalog_tests tests::test_rename_table ---
thread 'tests::test_rename_table' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyValue { backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/backtrace_shim.rs:15:19
      <catalog::error::EmptyValueSnafu>::build
             at src/error.rs:24:17
   1: <catalog::error::EmptyValueSnafu>::fail::<bool>
             at src/error.rs:24:17
   2: <catalog::remote::manager::RemoteCatalogManager as catalog::CatalogManager>::rename_table::{closure#0}
             at src/remote/manager.rs:470:24
   3: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<bool, catalog::error::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
   4: remote_catalog_tests::tests::test_rename_table::{closure#0}
             at tests/remote_catalog_tests.rs:296:13
```

**Comment by evenyag** [comment]
This PR changes lots of crates, I think it might be difficult to test and review these changes. I'm afraid the PR doesn't add enough tests to cover most cases, especially for the mito table engine and the storage engine. I'd recommend dividing the PR into several parts, each affecting a few crates, as the tracking issue #723  lists.

As for this PR, you could only retain the changes to the parser, but throw an error to tell users this feature is not supported yet.

**Comment by e1ijah1** [comment]
> This PR changes lots of crates, I think it might be difficult to test and review these changes. I'm afraid the PR doesn't add enough tests to cover most cases, especially for the mito table engine and the storage engine. I'd recommend dividing the PR into several parts, each affecting a few crates, as the tracking issue #723 lists.
> 
> As for this PR, you could only retain the changes to the parser, but throw an error to tell users this feature is not supported yet.

OK, thanks for your suggestion. I will close this pr and split these changes into several prs for submission.

**Pull request closed without merging**
