### PR TITLE
perf: merge small byte ranges for optimized fetching

### LINKED ISSUE #3072: Merge the small read io
Too many small requests could result in an expensive bill; there is an optimization we can do in the future(maybe not in this PR) for object stores like s3. If the `ranges` are almost continuous, we can merge these ranges into a large chunk and fetch this chunk in the preferred size concurrently.

_Originally posted by @WenyXu in https://github.com/GreptimeTeam/greptimedb/pull/2959#discussion_r1432230759_

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

close #3072 

## What's changed and what's your intention?

Merge small byte ranges for optimized fetching. 

BTW, For our use case, each row group limit of 102400 rows, the size is typically very small (i.e. ~1MiB).

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Comment by Xuanwo** [comment]
Enjoy using OpenDAL! Please let me know if there are any benchmarks to share.

**Comment by WenyXu** [comment]
> Enjoy using OpenDAL! Please let me know if there are any benchmarks to share.

@evenyag said the day before yesterday that he would benchmark it🤣

**Comment by evenyag** [comment]
> Enjoy using OpenDAL! Please let me know if there are any benchmarks to share.

Hope that I can finish the benchmark today 😢

**Review by evenyag — APPROVED** [review]
🚀  Up to 2x faster than before (The total query execution time).

**Pull request merged**
