### PR TITLE
refactor: move options to common_options

### PR DESCRIPTION
**Pull request by WenyXu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

1. move metasrv options to common_options
2. move frontend options to common_options
3. move datanode options to common_options

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by sunng87** [comment]
Talked with @WenyXu this patch is to extract options/configurations so that we can reuse them without pull in the whole dependency tree of frontend/...

But having a module sits in `commons` tier while having upper concepts like `frontend`/`datanode`/`metasrv` may not be a perfect idea.

**Comment by MichaelScofield** [comment]
@sunng87 make it a standalone crate "config" instead of "commons-options"?

**Comment by sunng87** [comment]
@MichaelScofield `config` sounds like a better name for this module.

Another issue with a shared config module between `servers`/`metasrv`/`frontend`/`datanode` is that `servers` can see configuration items of its upper tier modules like `frontend`. It's not a big deal for now, but there is a potential with dependency issue in future.

**Comment by MichaelScofield** [comment]
@sunng87 so we need a careful design to eliminate the potential circle deps. I think we can make crate `servers` not depends on crate `config`. `metasrv`/`frontend`/`datanode` can depends on `config`. When the three need to start servers, they create the options that servers needed and pass through.

**Comment by MichaelScofield** [comment]
@WenyXu Is it possible to move those structs out to crate `config`?

**Pull request closed without merging**
