### PR TITLE
feat: initial implementation of AlterDatabaseProcedure

### PR DESCRIPTION
**Pull request by NiwakaDev**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Related to #4394 

## What's changed and what's your intention?

This PR implements initial `AlterDatabaseProcedure`.
## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new module for altering databases, enhancing database management capabilities.
	- Added a new procedure for altering databases within a distributed system.
  
- **Bug Fixes**
	- Minor formatting adjustments and comments added for clarity, improving overall code readability.

### CODE REVIEW

**Comment by waynexia** [comment]
@coderabbitai pause

**Comment by CookiePieWw** [comment]
Hi @NiwakaDev, I've noticed the pr has been stuck for a while. If you're busy recently, I'd like to help to push forward this based on this pr :)

**Comment by NiwakaDev** [comment]
@CookiePieWw 

> I've noticed the pr has been stuck for a while. If you're busy recently, I'd like to help to push forward this based on this pr :)

I've already implemented the demo. I'll divide into multiple PRs and then going to submit them in turn.

**Comment by CookiePieWw** [comment]
> I've already implemented the demo. I'll divide into multiple PRs and then going to submit them in turn.

Got you :) call me if you need any help

**Comment by WenyXu** [comment]
Hi @NiwakaDev,  

Apologies for bringing this up again, but we’d like to include this feature in the upcoming v0.10 release. If you’re busy recently, I’d be happy to help push it forward based on your work. Please let me know if that works for you!

**Comment by NiwakaDev** [comment]
@WenyXu 

Is it better to submit a full PR?
I'm not sure how the initial PR get merged.

**Comment by WenyXu** [comment]
> @WenyXu
> 
> Is it better to submit a full PR? I'm not sure how the initial PR get merged.

Hi @NiwakaDev,

Thanks for your quick reply! Submitting a full PR sounds great. However, since we’re aiming to release v0.10 tomorrow, the timeline might be a bit tight. To ensure we can finalize it in time, would you be open to having @CookiePieWw collaborate with you to help push the changes forward?

Let us know your thoughts!

**Comment by NiwakaDev** [comment]
> Thanks for your quick reply! Apologies for the rush—this has become a priority due to a last-minute request from our CEO.

@WenyXu  @CookiePieWw  @killme2008 

Sorry for blocking your business. I'd like to contribute something if any chances and if you don't mind.

**Comment by killme2008** [comment]
@NiwakaDev 
For similar cases in the future, we will communicate with the contributors in advance, rather than rushing like this. Thank you again for your understanding.

**Pull request closed without merging**
