### PR TITLE
fix: add slash after generated region_dir

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

```sql
MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
| t       |
+---------+
3 rows in set (0.013 sec)

MySQL [(none)]> drop table t;
Query OK, 1 row affected (0.004 sec)

MySQL [(none)]> show tables;
+---------+
| Tables  |
+---------+
| numbers |
| scripts |
+---------+
2 rows in set (0.001 sec)
```

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
closes https://github.com/GreptimeTeam/greptimedb/issues/2457

### CODE REVIEW

**Review by WenyXu — APPROVED** [review]
verbose: We need always keep in mind all directory paths should end with `/`

**Comment by evenyag** [comment]
We still need to sanitize the dir in mito2, as I mentioned in https://github.com/GreptimeTeam/greptimedb/issues/2457#issuecomment-1728701801

**Comment by killme2008** [comment]
I think we can normalize the path when creating or opening regions.

**Comment by evenyag** [comment]
This is related to the correctness of mito2. If `region_dir` must end with `/`, then mito2 should return an error, or sanitize the directory.

**Review by fengjiachun — APPROVED** [review]

**Pull request merged**
