### PR TITLE
feat: redact secrets in sql when logging

### PR DESCRIPTION
**Pull request by MichaelScofield**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

The SQL will be printed in logs as is when it executes with an error, this could leak sensetive secrets. For example, the following SQL contains access key to S3:

```sql
COPY 'my_table' FROM '/test.orc' WITH (FORMAT = 'orc') CONNECTION(ENDPOINT = 's3.storage.site', REGION = 'hz', ACCESS_KEY_ID='my_key_id', SECRET_ACCESS_KEY="my_access_key");
```

This PR redacted the secrets in sql when logging. After redacted, the above sql is seen as

```sql
COPY 'my_table' FROM '/test.orc' WITH (FORMAT = 'orc') CONNECTION(ENDPOINT = 's3.storage.site', REGION = 'hz', ACCESS_KEY_ID='******', SECRET_ACCESS_KEY="******");
```

in logs.

Redaction is simply done by regex pattern matching on common seen secrets values.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by sunng87 — APPROVED** [review]
LGTM as a temporary solution. It's better to built it into logging macro as a permanent one

**Comment by MichaelScofield** [comment]
@sunng87 regex is not free, I think we'd better keep it outside of normal logging macros

**Comment by waynexia** [comment]
In my perspective, forbidding secrets shown in SQL might be a more proper way by using tools like [session variables](https://www.postgresql.org/docs/current/sql-set.html) or [stage](https://docs.snowflake.com/en/user-guide/data-load-s3-copy#loading-your-data). It's hard to redact every SQL before logging it out.

**Comment by MichaelScofield** [comment]
@waynexia you are right, it's best not to carry any secrets in sql. However, neither the session variable nor the stage could be done in short time, redaction like this is a temporary but fast solution. Leak already happened, better stop it quick.

**Review by killme2008 — APPROVED** [review]
LGTM

**Pull request merged**
