### PR TITLE
fix: compile error in develop branch

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

The last CI of #1354 ran before #1340 merged. And #1340 renames a function, which caused this compile error after #1354 merged into develop.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by waynexia** [comment]
By the way, it looks like there is no method that can execute `QueryStatement`. We need to do a match before calling the executor. cc @MichaelScofield

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Review by evenyag — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
I think this function name should be kept as `execute_stmt`, looks like the CR advice is not taken in https://github.com/GreptimeTeam/greptimedb/pull/1340 cc @MichaelScofield

**Comment by waynexia** [comment]
>The entry point for executing sqls is in frontend's instance, there's a StatementExecutor::execute_stmt that can execute QueryStatement directly. @waynexia

Thanks @MichaelScofield , I find it.

I look around and make a list of public `execute_*()` method list:
- struct method `StatementExecutor::execute::stmt()`, accepts `QueryStatement`
- struct method `StatementExecutor::plan_exec()`, accepts `QueryStatement`
- struct method `StatementExecutor::execute_sql()`, accepts `Statement`
- trait method `SqlStatementExecutor::execute_sql()`, accepts `Statement`
- struct method `StatementExecutor::execute_tql()`, accepts `Tql`,

Do you think we can find some way to unify them? Like only exposing one method that accepts the enum `QueryStatement`, and maybe defining it as a trait method. From my perspective of view, methods executing only one input like `Statement` or `LogicalPlan` need not go public.

**Comment by MichaelScofield** [comment]
@waynexia `plan_exec` can be private, I'll fix it. Only `execute_stmt` is pub, takes `QueryStatement` as input.

**Pull request merged**
