### PR TITLE
refactor: replace DfLogicalPlan with datafusion_expr::LogicalPlan

### PR DESCRIPTION
**Pull request by sunheyi6**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
as title, part of https://github.com/GreptimeTeam/greptimedb/issues/3884
## What's changed and what's your intention?

As the title said.

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

## Summary by CodeRabbit

- **Refactor**
  - Updated module imports to use `datafusion_expr::LogicalPlan` for improved code maintainability.

### CODE REVIEW

**Comment by evenyag** [comment]
Thanks for submitting the PR. To remove the wrapper type, we also need to remove the definition of our `LogicalPlan` and use Datafusion's `LogicalPlan` directly.
```rust
#[derive(Clone, Debug)]
pub enum LogicalPlan {
    DfPlan(DfLogicalPlan),
}
```

You can refer to https://github.com/GreptimeTeam/greptimedb/pull/3995 which removes the wrapper type for `Expr`.

**Comment by killme2008** [comment]
@sunheyi6 A conflict has to be resolved.

**Comment by sunheyi6** [comment]
> @sunheyi6 A conflict has to be resolved.

OK, I'll handle it right away.

**Comment by evenyag** [comment]
Please fix the compiler errors
https://github.com/GreptimeTeam/greptimedb/actions/runs/10000323455/job/27646084014?pr=4384

**Comment by sunheyi6** [comment]
> Please fix the compiler errors https://github.com/GreptimeTeam/greptimedb/actions/runs/10000323455/job/27646084014?pr=4384

ok，i will fix

**Comment by evenyag** [comment]
https://github.com/GreptimeTeam/greptimedb/blob/main/CONTRIBUTING.md#before-pr
Please refer to the contributing guide to run all tests and the clippy check locally first. Also please make sure your code can compile.

**Pull request closed without merging**
