### PR TITLE
ci: upgrade spell checker to 1.13.10

### PR DESCRIPTION
**Pull request by hezhizhen**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Upgrade typos-cli from 1.0.4 to 1.13.10.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by killme2008** [comment]
👍  Cool, can you fix the typos found in this PR?  See https://github.com/GreptimeTeam/greptimedb/pull/1045/files

Thanks a lot.

**Comment by hezhizhen** [comment]
> 

I was working on it, and now it's done. Please take a look.

**Comment by hezhizhen** [comment]
@killme2008 The output of `taplo` is quite simple and I don't know what to do based on that, so I have to install it locally and run it locally. Should we add it to Makefile or `.pre-commit-config.yaml` to make sure all TOML files meet its need?

**Comment by waynexia** [comment]
>Should we add it to Makefile or .pre-commit-config.yaml to make sure all TOML files meet its need?

Sounds great. We can add a Makefile target for `taplo format --check --option "indent_string=    "`. But I'm not sure if there is a precommit hook for taplo.

**Comment by hezhizhen** [comment]
> > Should we add it to Makefile or .pre-commit-config.yaml to make sure all TOML files meet its need?
> 
> Sounds great. We can add a Makefile target for `taplo format --check --option "indent_string= "`. But I'm not sure if there is a precommit hook for taplo.

I've added it to Makefile.

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by hezhizhen** [comment]
`coverage` failed. I don't know why and how to fix it...

**Comment by waynexia** [comment]
> `coverage` failed. I don't know why and how to fix it...

It's codecov's bug. I've retried it.

**Review by waynexia — APPROVED** [review]
look good to me, thanks @hezhizhen!

**Comment by hezhizhen** [comment]
> > `coverage` failed. I don't know why and how to fix it...
> 
> It's codecov's bug. I've retried it.

Still failed...

**Pull request merged**
