### PR TITLE
feat: add more spans to mito engine

### PR DESCRIPTION
**Pull request by lyang24**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
https://github.com/GreptimeTeam/greptimedb/issues/4480

## What's changed and what's your intention?
This commit adds more spans into mito engine to give better insights on debugging slow queires.
For reads i enhanced spans on reader building time.

__!!! DO NOT LEAVE THIS BLOCK EMPTY !!!__

Please explain IN DETAIL what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

### CODE REVIEW

**Review by MichaelScofield — APPROVED** [review]

**Comment by WenyXu** [comment]
How about setting the tracing level to Debug? i.e., `#[instrument(level = Level::DEBUG, ...)]`

**Comment by lyang24** [comment]
> How about setting the tracing level to Debug? i.e., `#[instrument(level = Level::DEBUG, ...)]`

done

**Comment by discord9** [comment]
Calls that occur very frequently and are typically not time-consuming, such as `write_to_wal` or `next_batch`, can be set to a tracing level of TRACE to avoid excessive verbosity during debug mode, or those traces could be completely removed to prevent pref regression(Removing might be unnecessary since tracing is essentially a comparison to an integer when not enabled, and branch prediction could minimize the time cost significantly, might only see 0.5%~1% regression in speed)

**Comment by lyang24** [comment]
> Calls that occur very frequently and are typically not time-consuming, such as `write_to_wal` or `next_batch`, can be set to a tracing level of TRACE to avoid excessive verbosity during debug mode, or those traces could be completely removed to prevent pref regression(Removing might be unnecessary since tracing is essentially a comparison to an integer when not enabled, and branch prediction could minimize the time cost significantly, might only see 0.5%~1% regression in speed)

thanks for the feedback i agree that adding spans on frequently called methods might not be very helpful and it could be verbose and leads to potential perf regression so i removed them. Please let me know if there are places in mito2 engine that should be traced that i missed in this pr.

**Review by WenyXu — APPROVED** [review]

**Pull request merged**
