### PR TITLE
fix: construct correct pk list with pre-existing pk

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

Closes https://github.com/GreptimeTeam/greptimedb/issues/3612

## What's changed and what's your intention?

The previous test doesn't cover creating physical table with some primary keys

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by waynexia** [comment]
CI failure fix: https://github.com/GreptimeTeam/greptimedb/pull/3616

**Review by WenyXu — APPROVED** [review]
It works on my branch🤩

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@waynexia There is a test failure:

```
--- TRY 1 STDERR:        metric-engine engine::create::test::test_create_request_for_data_region ---
thread 'engine::create::test::test_create_request_for_data_region' panicked at src/metric-engine/src/engine/create.rs:610:9:
assertion `left == right` failed
  left: [2147483652, 2147483651, 1]
 right: [2147483652, 2147483651]
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed::<alloc::vec::Vec<u32>, alloc::vec::Vec<u32>>
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:297:5
   4: metric_engine::engine::create::test::test_create_request_for_data_region::{closure#0}
             at ./src/engine/create.rs:610:9
   5: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/future/future.rs:124:9
   6: <core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/future/future.rs:124:9
   7: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/current_thread/mod.rs:665:57
   8: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba1500
```

**Pull request merged**
