### PR TITLE
feat: support time range in copy table

### PR DESCRIPTION
**Pull request by v0y4g3r**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

This PR adds support for specifying time range to export when executing `COPY <TABLE> TO` statement.

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.
- [ ]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by evenyag** [comment]
Sqlness test is failed

**Comment by v0y4g3r** [comment]
> Sqlness test is failed

@WenyXu is fixing sqlness suites.

**Comment by evenyag** [comment]
> > Sqlness test is failed
> 
> @WenyXu is fixing sqlness suites.

The failure is time-zone related. I'm unsure why it occurs in this PR. @WenyXu @v0y4g3r 
```
Result unexpected, path:"./tests/cases/distributed/common/function/date.sql"
[
    ... skip(72) ...,
~   | 2023-12-06 07:39:46:222                                                    | -> | 2023-12-06 15:39:46:222                                                    |,
    ... skip(7) ...,
~   | 2023-12-06 07:39:46:000                                                    | -> | 2023-12-06 15:39:46:000                                                    |,
    ... skip(120) ...,
~   | 1992-01-01 00:00:00:000                            | -> | 1992-01-01 08:00:00:000                            |,
~   | 1993-12-30 00:00:00:000                            | -> | 1993-12-30 08:00:00:000                            |,
~   | 2023-12-06 00:00:00:000                            | -> | 2023-12-06 08:00:00:000                            |,
    ... skip(7) ...,
~   | 1970-01-01 00:00:00:001                             | -> | 1970-01-01 08:00:00:001                             |,
~   | 1970-01-01 00:00:00:002                             | -> | 1970-01-01 08:00:00:002                             |,
~   | 1970-01-01 00:00:00:003                             | -> | 1970-01-01 08:00:00:003                             |,
    ... skip(6) ...
]
```

**Review by MichaelScofield — APPROVED** [review]
need this asap

**Review by evenyag — APPROVED** [review]
LGTM

**Pull request merged**
