### PR TITLE
build(deps): remove some unused dependencies

### PR DESCRIPTION
**Pull request by dimbtp**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

It takes quite long time to build the project on my laptop, so I tried to remove
some dependencies to see whether it will improve the compile time.

From my local test with
- command `cargo build --timings` after `cargo clean` the cache
- 8 threads
- 16GB memory (about 15GB free)
- clang version 16.0.6
- reboot system and compile directly to reduce the affect of other stuffs

before: 
before
after:
after

However, I only observed very little improvement except units reduce from 1229
to 1219. The compilation will drain all my memory and sometimes crash my GUI,
so maybe better hardware can give more improvements?

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by waynexia** [comment]
>However, I only observed very little improvement except units reduce from 1229
to 1219. 

Most of the unused deps you removed in this patch are still dependent in other places so the overall compile time doesn't change a lot. But still appreciate it 💯

**Comment by dimbtp** [comment]
Only test `cargo build` locally 😅, try to test others. Or this job has already been done?

**Comment by dimbtp** [comment]
> Have you tried the [mold](https://github.com/rui314/mold)? It only takes ~4GiB memory for `cargo build`.

Test it and time reduces from `461.4s (7m 41.4s)` to `374.0s (6m 14.0s)`, really boost a lot. Thanks ❤️!

What do you mean `~4GiB memory for cargo build`? As compilation still drain almost all of my free memory.

**Comment by waynexia** [comment]
> Have you tried the [mold](https://github.com/rui314/mold)? It only takes ~4GiB memory for `cargo build`.

Maybe we should mention this somewhere in our document. In my experience `mold` helps in many environments.

cc @tisonkun do you have any suggestions for the place?

**Comment by tisonkun** [comment]
> Maybe we should mention this somewhere in our document. In my experience mold helps in many environments.

@waynexia it can be a subtask of a revision of CONTRIBUTING.md. You can create an issue and ping me. I schedule to handle the CONTRIBUTING.md file in April; any feedback is welcome :D

**Comment by waynexia** [comment]
> > Maybe we should mention this somewhere in our document. In my experience mold helps in many environments.
> 
> @waynexia it can be a subtask of a revision of CONTRIBUTING.md. You can create an issue and ping me. I schedule to handle the CONTRIBUTING.md file in April; any feedback is welcome :D

Ticket: https://github.com/GreptimeTeam/greptimedb/issues/3587

**Review by tisonkun — APPROVED** [review]
Then let's go?

**Review by WenyXu — APPROVED** [review]

**Pull request merged**
