### PR TITLE
feat: reload user provider

### PR DESCRIPTION
**Pull request by tisonkun**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

This is a draft related to #1862.

But I found an issue -

`UserProvider` is immutable and hard to access in Query/Execute context.

Shall we even make it mutable? Where we should implement this mutation and access to the provider?

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [x]  This PR does not require documentation updates.

### CODE REVIEW

**Comment by shuiyisong** [comment]
> `UserProvider` is immutable and hard to access in Query/Execute context.

`UserProvider` is not designed to be accessed during query / execution. Its sole purpose is to provide an `UserInfo` upon connection. `UserInfo` is later set into `QueryContext` and retrieved if needed during query / execution.

**Comment by tisonkun** [comment]
Hack to impl. Test locally that such `ALTER SYSTEM RELOAD USERPROVIDER` can work.

But as @shuiyisong stated above, we may even not to "implement" it.

**Comment by tisonkun** [comment]
I suppose that "StaticUserProvider" means it's static. If users want a dynamic one, they can implement their own plugin and dynamic load credential in their provider's implementation?

**Comment by tisonkun** [comment]
Closed. But the implement "TryFrom<&str>" can be improved. Such TryFrom is semantically confusing.

**Pull request closed without merging**
