### PR TITLE
docs: Adds more panels to grafana dashboards

### PR DESCRIPTION
**Pull request by evenyag**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?
This PR adds more panels to our grafana dashboards.

For the standalone dashboard
- HTTP request rate
- Cache size
- Cache hit rate
- WAL store sync duration

For the cluster dashboard
- Cache size
- Cache hit rate
- Query stage elapsed time
- Write stall

It fixes some issues with the standalone dashboard:
- replaces all hard-coded rate intervals (`[2s]`) with `$__rate_interval`, otherwise many panels don't work well if the scrape is larger than 2s
- fixes the write stall count panel
- uses uppercase titles

For cluster dashboard:
- renames `greptime_pod` to `instance` as we don't always have the `greptime_pod` label
- export externally (The previous dashboard json is exported for internal use)

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

## Summary by CodeRabbit

- **New Features**
	- Enhanced Grafana dashboard with updated metric expressions for improved data accuracy.
	- Modified panel titles for better clarity on displayed metrics.
	- Introduced new metrics and restructured the dashboard layout for optimized monitoring.

- **Bug Fixes**
	- Corrected legend formats to show specific instance names instead of automatic labels.

- **Documentation**
	- Improved insights and actionable data presentation in the monitoring system.

### CODE REVIEW

**Comment by waynexia** [comment]
What are "more panels"? You basically write no description

**Comment by fengjiachun** [comment]
5741 / 1000 = 5 red envelops

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by evenyag** [comment]
@coderabbitai summary

**Comment by evenyag** [comment]
> What are "more panels"? You basically write no description

Someone urged me to have dinner with them on Friday, so I didn't have enough time to write the description.

I'm going to further adjust the cluster dashboard so I will convert this PR to draft again.

**Review by shuiyisong — APPROVED** [review]

**Pull request merged**
