### PR TITLE
feat: information schema

### LINKED ISSUE #834: Panic when select the system.information_schema.system_catalog table
### What type of bug is this?

Crash

### What subsystems are affected?

Standalone mode, Frontend, Datanode

### What happened?

The server panic if we try to execute `select * from system.information_schema.system_catalog;`

### What operating system did you use?

All

### Relevant log output and stack trace

```bash
2023-01-05T06:59:59.491339Z ERROR common_telemetry::panic_hook: panicked at 'System catalog table does not support scan!', src/catalog/src/system.rs:68:9 backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
             at src/common/telemetry/src/panic_hook.rs:30:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/panicking.rs:64:14
   6: <catalog::system::SystemCatalogTable as table::table::Table>::scan::{{closure}}
             at src/catalog/src/system.rs:68:9
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
   8: <table::table::adapter::DfTableProviderAdapter as datafusion::datasource::datasource::TableProvider>::scan::{{closure}}
             at src/table/src/table/adapter.rs:77:65
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
  10: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /home/jkshen/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/4917235/datafusion/core/src/physical_plan/planner.rs:488:88
```

### How can we reproduce the bug?

```bash
select * from system.information_schema.system_catalog;
```

### LINKED ISSUE #1251: information_schema.TABLES support for mysql protocol
### What type of enhancement is this?

API improvement

### What does the enhancement do?

A few visualization or BI tools, grafana for example, has query builders to help user to construct a query. These query builders retrieve table information from a table called `information_schema.TABLES` in mysql: https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.0/en/information-schema-tables-table.html

At the moment if we configure greptimedb as a grafana mysql data source, it error at this query:
```
Failed to execute query 'SELECT DISTINCT TABLE_SCHEMA from information_schema.TABLES where TABLE_TYPE != 'SYSTEM VIEW' ORDER BY TABLE_SCHEMA' err.msg=Failed to execute query: SELECT DISTINCT TABLE_SCHEMA from information_schema.TABLES where TABLE_TYPE != 'SYSTEM VIEW' ORDER BY TABLE_SCHEMA,
```

We don't need to implement this schema or table actually but should be able to respond queries like this, in order to provide better usability with tools depend on it.

### Implementation challenges

Since mysql is not designed with multi-tenancy in mind, we should carefully deal with the query under it's context of greptimedb's catalog and schema.

### PR DESCRIPTION
**Pull request by MichaelScofield**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Add basic support for information schema. Just reuse the one in DataFusion (also update the DataFusion of course).

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)

close #1251

fix #834

### CODE REVIEW

**Comment by MichaelScofield** [comment]
no implicit filters, iterating all catalogs (and schemas, tables) that exist in catalog list @sunng87

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Comment by v0y4g3r** [comment]
BTW should we provide some per-table stats, like rows and disk usage in information schema?

**Comment by MichaelScofield** [comment]
I don't think the stats should be reported in information schema. that said, I'm not biased, we can postpone implementing it if it's demand. for now we just reuse datafusion's implementation

**Comment by sunng87** [comment]
We need those constraints to be able to use in multi-tenant environment. Like [postgres](https://www.postgresql.org/docs/current/infoschema-tables.html), it only shows tables that current user has access to.

**Comment by MichaelScofield** [comment]
Pg’s database is logically one level above the catalog. Currently we lack this kind of multi-tenancy support, it’s planned in #247 . I think as to this information schema’s concern, we can postpone it thereafter. Maybe we can create a catalog list for each tenant, then the problem is easily solved.

**Comment by MichaelScofield** [comment]
@sunng87 Now the user can only see information schema under current catalog. You can check the test `instance_test::test_information_schema`.

**Review by sunng87 — APPROVED** [review]

**Comment by waynexia** [comment]
Do we need to update the doc? @MichaelScofield

**Pull request merged**
