### PR TITLE
feat: prevent sensitive information (key, password, secrets etc.) from being printed in plain

### LINKED ISSUE #1487: prevent sensitive information (key, password, secrets etc.) from being printed in plain
### What type of enhancement is this?

Configuration, User experience

### What does the enhancement do?

Sensitive information might get leaked by being printed out for debugging purposes. It should be avoided in (any?) condition.

This can be archived by using a new type wrapper to override `Display` or `Debug` for sensitive fields

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by DevilExileSu**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?
add secret type, `SecretString` and `SecretBytes`.

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
close #1487

### CODE REVIEW

**Comment by DevilExileSu** [comment]
In [common::base::Bytes](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/common/base/src/bytes.rs#L23), because `Bytes` implements `Deref`, the `len()` and `is_empty()` seem to be redundant.

**Review by evenyag — COMMENTED** [review]
I think we could use [secstr](https://crates.io/crates/secstr) to do this. @sunng87

**Comment by DevilExileSu** [comment]
> I think we could use [secstr](https://crates.io/crates/secstr) to do this. @sunng87

You are right, we can use  [secstr](https://crates.io/crates/secstr) or [secrecy](https://crates.io/crates/secrecy), which is more safe.

**Comment by sunng87** [comment]
Yes, it will be nice to use existing solutions.

**Comment by DevilExileSu** [comment]
The inner container of `serstr::SerStr` is `Vec<u8>`, which requires additional processing when deserializing toml string, and needs to convert `Vec<u8>` into `&str` when constructing `Instance`, so I use the more convenient `secrecy::SecretString`

**Review by sunng87 — APPROVED** [review]

**Review by evenyag — APPROVED** [review]

**Comment by evenyag** [comment]
> The inner struct of `serstr::SerStr` is `Vec<u8>`, which requires additional processing when deserializing toml string, and needs to convert `Vec<u8>` into `&str` when constructing `Instance`

secstr provides a [SecUtf8](https://docs.rs/secstr/latest/secstr/struct.SecUtf8.html). But using secrecy is fine, these two crates are similar.

> Bytes implements Deref, the len() and is_empty() seem to be redundant.

Oh, right, you could open a new PR for this.

> we can also implement Deref for BytesString.

I'm not sure, as BytesString might hold a non-UTF-8 string in the future. But we can implement Deref first since we only support UTF-8 strings now. Once it really needs to support non-UTF-8 encoding, we must remove the Deref impl and methods that access it as str directly.

**Comment by DevilExileSu** [comment]
> 

Thx! Got it. I'm ashamed that I didn't check the documentation for `secstr` carefully earlier.

**Pull request merged**
