### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by SSebo**

### CODE REVIEW

**Comment by waynexia** [comment]
Thanks for your contribution ❤️

We are setting up our CLA assignment. Let's make progress when it's ready.

**Review by waynexia — APPROVED** [review]

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by waynexia** [comment]
Hi @SSebo, we have made our CLA file at [here](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc), please check it out! If you agree with it please reply with the following line:

>I hereby agree to the terms of the GreptimeDB CLA: https://gist.github.com/xtang/6378857777706e568c1949c7578592cc

**Comment by killme2008** [comment]
Only the `test_s3_backend` fails, we will look into it. Thanks for your PR, please sign the CLA, thank you.

**Comment by SSebo** [comment]
I hereby agree to the terms of the GreptimeDB CLA: https://gist.github.com/xtang/6378857777706e568c1949c7578592cc 
@waynexia

**Comment by waynexia** [comment]
> I hereby agree to the terms of the GreptimeDB CLA: https://gist.github.com/xtang/6378857777706e568c1949c7578592cc @waynexia

Thanks!

**Pull request merged**
