### PR TITLE
feat: specify prom server start addr

### PR DESCRIPTION
**Pull request by yuanbohan**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

start prometheus API server with specified addr, so the `/query` and `/query_range` can be accessible outside of container by running the standalone mode: `cargo run -- standalone start --prom-addr=0.0.0.0:4004`

### CODE REVIEW

**Comment by waynexia** [comment]
`promql-server` will change to `prometheus` ([discuss](https://github.com/GreptimeTeam/greptimedb/pull/924#issuecomment-1413560052)). So for this PR we'd better name the config `prometheus-server`

**Review by waynexia — APPROVED** [review]
LGTM

**Review by evenyag — APPROVED** [review]
LGTM. Now we have two similar configurations `prometheus_options` and `prom_options`...... Could you also update the configuration reference in our [docs repo](https://github.com/GreptimeTeam/docs/blob/main/docs/reference/configuration.md)?

**Comment by evenyag** [comment]
> `promql-server` will change to `prometheus` ([discuss](https://github.com/GreptimeTeam/greptimedb/pull/924#issuecomment-1413560052)).

Shall we create an issue for this? I'm not sure whether we already have an issue tracking this.

**Comment by waynexia** [comment]
> > `promql-server` will change to `prometheus` ([discuss](https://github.com/GreptimeTeam/greptimedb/pull/924#issuecomment-1413560052)).
> 
> Shall we create an issue for this? I'm not sure whether we already have an issue tracking this.

Sure: https://github.com/GreptimeTeam/greptimedb/issues/1127

**Pull request merged**
