### PR TITLE
feat: handle AND/OR and priority in matches fn

### PR DESCRIPTION
**Pull request by waynexia**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

The **A** in AST is for abstract. So does this patch

## Checklist

- [x] I have written the necessary rustdoc comments.
- [x] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

## Summary by CodeRabbit

- **New Features**
  - Enhanced pattern matching functionality for more efficient and flexible pattern expressions.

- **Refactor**
  - Restructured AST transformation process for improved code readability and maintainability.

### CODE REVIEW

**Comment by waynexia** [comment]
@coderabbitai pause

**Review by killme2008 — COMMENTED** [review]
Looks good to me. I have a question: how can we match string literals that are keywords, such as `AND` and `OR`? Is there a way to escape them?

**Comment by waynexia** [comment]
> Looks good to me. I have a question: how can we match string literals that are keywords, such as `AND` and `OR`? Is there a way to escape them?
> 

quote them should fine. I'll add a test case for this.

**Review by killme2008 — APPROVED** [review]
LGTM

**Review by fengjiachun — APPROVED** [review]
LGTM

**Pull request merged**
